#!/usr/bin/env node
/**
 * fetchFonts.mjs — Download the woff2 files for Noto Sans Georgian and
 * Noto Serif Georgian from Google Fonts and emit a self-hosted CSS
 * stylesheet at src/assets/styles/noto-georgian.css.
 *
 * Why: timeline-geo's audience is primarily Georgian-speaking. Depending
 * on fonts.googleapis.com / fonts.gstatic.com is a hedge against networks
 * that block Google CDNs. See issue #61.
 *
 * Usage: `node scripts/fetchFonts.mjs`
 *
 * The script keeps only the `georgian` and `latin` subsets (Latin is
 * needed for English text in EN locale and for any Latin code/numbers
 * embedded in KA pages). Other subsets — cyrillic, greek, math, symbols,
 * latin-ext — are intentionally dropped to keep the asset footprint tiny.
 */

import { writeFile, mkdir, readFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const FONT_DIR = resolve(ROOT, 'public', 'fonts')
const CSS_OUT = resolve(ROOT, 'src', 'assets', 'styles', 'noto-georgian.css')

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

// Only keep these subsets — see header comment.
const KEPT_SUBSETS = new Set(['georgian', 'latin'])

const FAMILIES = [
  {
    family: 'Noto Sans Georgian',
    cssUrl:
      'https://fonts.googleapis.com/css2?family=Noto+Sans+Georgian:wdth,wght@75,300;75,400;75,600;75,700&display=swap',
    filePrefix: 'noto-sans-georgian',
  },
  {
    family: 'Noto Serif Georgian',
    cssUrl:
      'https://fonts.googleapis.com/css2?family=Noto+Serif+Georgian:wght@600&display=swap',
    filePrefix: 'noto-serif-georgian',
  },
]

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`)
  return res.text()
}

async function fetchBuffer(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`)
  return Buffer.from(await res.arrayBuffer())
}

/** Parse the Google CSS into [{subset, block}], where each block ends in a `}`. */
function parseBlocks(css) {
  const blocks = []
  // Each entry is preceded by a `/* subset-name */` comment.
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi
  let m
  while ((m = re.exec(css))) {
    blocks.push({ subset: m[1], block: m[2] })
  }
  return blocks
}

function rewriteSrc(block, localPath) {
  return block.replace(/url\([^)]*\)/, `url('${localPath}')`)
}

function fontFilename(filePrefix, subset) {
  // Google serves the same variable woff2 for every weight in our wght
  // axis, so we don't include weight in the filename — one georgian +
  // one latin file per family is enough.
  return `${filePrefix}-${subset}.woff2`
}

async function processFamily({ family, cssUrl, filePrefix }) {
  console.log(`Fetching ${family}...`)
  const css = await fetchText(cssUrl)
  const blocks = parseBlocks(css)
  const kept = blocks.filter((b) => KEPT_SUBSETS.has(b.subset))
  console.log(`  ${blocks.length} subset blocks, keeping ${kept.length} (${[...new Set(kept.map((k) => k.subset))].join(', ')})`)

  const downloaded = new Map() // remoteUrl → localPath
  const outBlocks = []
  for (const { subset, block } of kept) {
    const urlMatch = block.match(/url\((https:\/\/[^)]+)\)/)
    const weightMatch = block.match(/font-weight:\s*(\d+)/)
    if (!urlMatch || !weightMatch) {
      console.warn(`  skipping malformed block:`, block.slice(0, 80))
      continue
    }
    const remoteUrl = urlMatch[1]
    let localPath = downloaded.get(remoteUrl)
    if (!localPath) {
      const filename = fontFilename(filePrefix, subset)
      localPath = `/fonts/${filename}`
      const filePath = resolve(FONT_DIR, filename)
      if (!existsSync(filePath)) {
        console.log(`    downloading ${filename}`)
        const buf = await fetchBuffer(remoteUrl)
        await writeFile(filePath, buf)
      } else {
        console.log(`    ${filename} already present, skipping`)
      }
      downloaded.set(remoteUrl, localPath)
    }
    outBlocks.push(rewriteSrc(block, localPath))
  }
  return outBlocks
}

async function main() {
  await mkdir(FONT_DIR, { recursive: true })
  await mkdir(dirname(CSS_OUT), { recursive: true })

  const allBlocks = []
  for (const family of FAMILIES) {
    const blocks = await processFamily(family)
    allBlocks.push(`/* ── ${family.family} ── */`, ...blocks)
  }

  const css =
    `/* AUTOGENERATED by scripts/fetchFonts.mjs — do not edit by hand.\n` +
    `   Re-run \`node scripts/fetchFonts.mjs\` to refresh. See issue #61. */\n\n` +
    allBlocks.join('\n\n') +
    '\n'
  await writeFile(CSS_OUT, css, 'utf8')
  console.log(`\nWrote ${CSS_OUT}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
